# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Keytographer < Formula
  desc "Beautiful keymap visualizations"
  homepage "https://github.com/chdorner/keytographer"
  version "0.1.0-alpha.1"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chdorner/keytographer/releases/download/v0.1.0-alpha.1/keytographer_0.1.0-alpha.1_Darwin_x86_64.tar.gz"
      sha256 "b485b4bca70bfa76275c6221611519f38b63e1924ae5dcc4382b07ca2a20f6f6"

      def install
        bin.install "keytographer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chdorner/keytographer/releases/download/v0.1.0-alpha.1/keytographer_0.1.0-alpha.1_Darwin_arm64.tar.gz"
      sha256 "c8e5b190857745fc04527aa085a87bc63953ee45770ff89c5644a722d40b5f3e"

      def install
        bin.install "keytographer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chdorner/keytographer/releases/download/v0.1.0-alpha.1/keytographer_0.1.0-alpha.1_Linux_arm64.tar.gz"
      sha256 "aa14f27003c833eb7c558bc1c64284110c570b1e0161ed41a3a40bc9570af6ff"

      def install
        bin.install "keytographer"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chdorner/keytographer/releases/download/v0.1.0-alpha.1/keytographer_0.1.0-alpha.1_Linux_x86_64.tar.gz"
      sha256 "c940b1795335db385833d742740ee3304441a32da2a46a8b89a6375bead0e3ec"

      def install
        bin.install "keytographer"
      end
    end
  end
end
